endereco/urls.py
from django.urls import path
from .views import AddressCreate, AddressList, AddressUpdate, AddressDetail, AddressDelete, cep_search_view

app_name = 'endereco'

urlpatterns = [
    path('cep/', cep_search_view, name='cep'),


    path('criar/', AddressCreate.as_view(), name='criar'),
    path('listar/', AddressList.as_view(), name='listar'),
    path('detalhes/<int:pk>', AddressDetail.as_view(), name="detalhar"),
    path('editar/<int:pk>', AddressUpdate.as_view(), name="atualizar"),
    path('deletar/<int:pk>', AddressDelete.as_view(), name="deletar"),
    
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('endereco/', include('endereco.urls'))
]

endereco/models.py
from django.db import models

class Address(models.Model):
    cep = models.CharField(max_length=9)
    logradouro = models.CharField(max_length=50)
    bairro = models.CharField(max_length=30)
    localidade = models.CharField(max_length=30)
    uf = models.CharField(max_length=2)


# Create your models here.

endereco/forms.py
from django import forms
from .models import Address

class CepForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['cep', 'logradouro', 'bairro', 'localidade', 'uf']
        labels = {
            'cep': 'CEP',
            'logradouro': 'Rua',
            'bairro': 'Bairro',
            'localidade': 'Cidade',
            'uf': 'UF',
        }

        widgets = {
            'cep': forms.TextInput(attrs={'class': 'form-control'}),
            'logradouro': forms.TextInput(attrs={'class': 'form-control'}),
            'bairro': forms.TextInput(attrs={'class': 'form-control'}),
            'localidade': forms.TextInput(attrs={'class': 'form-control'}),
            'uf': forms.TextInput(attrs={'class': 'form-control'}),
        }
class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['cep', 'logradouro', 'bairro', 'localidade', 'uf']
        labels = {
            'cep': 'CEP',
            'logradouro': 'Rua',
            'bairro': 'Bairro',
            'localidade': 'Cidade',
            'uf': 'UF',
        }

        widgets = {
            'cep': forms.TextInput(attrs={'class': 'form-control'}),
            'logradouro': forms.TextInput(attrs={'class': 'form-control'}),
            'bairro': forms.TextInput(attrs={'class': 'form-control'}),
            'localidade': forms.TextInput(attrs={'class': 'form-control'}),
            'uf': forms.TextInput(attrs={'class': 'form-control'}),
        }

endereco/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy
import requests 

from .models import Address
from .forms import AddressForm, CepForm

def cep_search_view(request):
    if request.method == 'GET':
        form = CepForm()

    message = ''

    if request.method == 'POST':
        form = CepForm(request.POST)

        cep_digitado = request.POST.get('cep')
        url = f"https://viacep.com.br/ws/{cep_digitado}/json/"
        response = requests.get(url)

        if response.status_code == 200:
            dados_cep = response.json()
            if 'erro' in dados_cep:
                message = 'CEP não encontrado'

            else: 
                reposta_em_json_filtrada = {
                    'cep': dados_cep['cep'],
                    'logradouro': dados_cep['logradouro'],
                    'bairro': dados_cep['bairro'],
                    'localidade': dados_cep['localidade'],
                    'uf': dados_cep['uf'],
                }
                form = CepForm(initial=reposta_em_json_filtrada)

                if form.is_valid():
                    form.save()
                
        else:
            message = "Erro durante a requisição a API"

    return render(request, 'endereco/cepSearch.html', {
        'form': form,
        'message': message
    })

class AddressCreate(CreateView):
    model = Address
    form_class = AddressForm
    context_object_name = 'CreateAddressForm'
    template_name = 'endereco/addressForm.html'
    success_url = reverse_lazy('endereco:list')

class AddressList(ListView):
    model = Address
    template_name = 'endereco/addressList.html'
    context_object_name = 'addressess'

class AddressUpdate(UpdateView):
    model = Address
    form_class = AddressForm
    context_object_name = 'address'
    template_name = 'endereco/addressForm.html'
    success_url = reverse_lazy('edndereco:listar')

class AddressDetail(DetailView):
    model = Address
    template_name = 'endereco/addressDetail.html'
    context_object_name = 'address'

class AddressDelete(DeleteView):
    model = Address
    template_name = 'endereco/addressDelete.html'
    success_url = reverse_lazy('endereco:listar')





# Create your views here.

endereco/templates/endereco/addressDelete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Remover</title>
</head>
<body>
    <h1>Confirme a remoção:</h1>
    <form action="{% url 'endereco:deletar' address.id %}" method="post">
        {% csrf_token %}
        <p>CEP: {{ address.cep }}</p>

        <button><a href="{% url 'endereco:listar' %}">Listar</a></button>
        <button><a href="{% url 'endereco:deletar' %}">Remover</a></button>
        <button type="submit">Remover</button>
    </form>
</body>
</html>

endereco/templates/endereco/addressDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes</title>
</head>
<body>
    <h1>Detalhes:</h1>
    <p>CEP: {{ address.cep }}</p>
    <p>Logradouro: {{ address.logradouro }}</p>
    <p>Bairro: {{ address.bairro }}</p>
    <p>Cidade: {{ address.cidade }}</p>
    <p>UF: {{ address.uf }}</p>

    <button><a href="{% url 'endereco:atualizar' address.id %}">Editar</a></button>
    <button><a href="{% url 'endereco:listar' address.id %}">Lista</a></button>
</body>
</html>

endereco/templates/endereco/addressForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>
<body>
    {% if address %}
        <h1>Editar</h1>
        <form action="{% url 'endereco:atualizar' address.id %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label_tag }}
                <br>
                {{ field }}
                <br>
            {% endfor %}
            <button type="submit">Atualizar</button>
        </form>
    {% endif %}
    <h1>Cadastrar Endereco</h1>
    <form action="{% url 'endereco:criar' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }}
            <br>
            {{ field }}
            <br>
        {% endfor %}
        <button type="submit">Cadastrar</button>
    </form>
</body>
</html>

endereco/templates/endereco/addressList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista</title>
</head>
<body>
    {% if addresses %}
        <h1>Endereço</h1>
        <table>
            <tr>
                <th>CEP</th>
                <th>Cidade</th>
                <th>UF</th>
                <th>Opções</th>
            </tr>
            {% for address in addressess %}
                <tr>
                    <td>{{ address.cep }}</td>
                    <td>{{ address.localidade }}</td>
                    <td>{{ address.uf }}</td>
                    <td>
                        <button><a href="{% url 'endereco/atualizar' address.id %}">Editar</a></button>
                        <button><a href="{% url 'endereco/detalhar' address.id %}">Detalhes</a></button>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
</body>
</html>

endereco/templates/endereco/cepSearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buscar e Salvar CEP</title>
</head>
<body>
    <h1>Digite o CEP para busca:</h1>
    {% if message %}
        <p>{{ message }}</p>
    {% endif %}

    <form method="post">
        {% csrf_token %}

        {% if not form.initial.logradouro %}
            <p>{{ form.cep.label_tag }}</p>
            <br>
            <p>{{ form.cep }}</p>
            <button type="submit">Buscar</button>

        {% else %}
            {{ form.as_p }}
        {% endif %}
    </form>
</body>
</html>